3p-recaptcha: Minor test improvement (#26915)
* 3p-recaptcha: Minor test improvement

Resolve sinon warning:

ERROR: 'The test "3p recaptcha.js should require a window.name" contains an "allowConsoleError" block that didn't result in a call to console.error.'

* Revert "3p-recaptcha: Minor test improvement"

This reverts commit a29224092b15e94336933654d8470f3caf190eaf.

* Remove expectation of console error