Sync from Google (#26856)
* Add JSON parser to validate json content in HTML.

PiperOrigin-RevId: 292678263

* 1) Introduce exclude char '^'
2) Implement range syntax.
3) Introduce '\u' identifier for non-ascii character match.

PiperOrigin-RevId: 293155674

* Add IsWhitespaceChar function that determines if a character at a given
position is a whitespace char including any unicode whitespace.

PiperOrigin-RevId: 293718940

* Adds Strings::SplitStrAtUtf8Whitespace string util method.

PiperOrigin-RevId: 293834550

* Fix build errors.

PiperOrigin-RevId: 293885884

* Fix strings::Escape

PiperOrigin-RevId: 293897944

* JSON grammer do not allow trailing commas [1,] {"a":"b",}.

Fixes this. Previously trailing commas were considered OK.

START_PUBLIC
Fix trailing comma in json parser.

PiperOrigin-RevId: 294938254

* Internal refactoring.

PiperOrigin-RevId: 294983985

* Prettify entities.json

PiperOrigin-RevId: 295032659

* Add missing licenses and other clean up.

PiperOrigin-RevId: 295033719

* Remove license comment from JSON file

PiperOrigin-RevId: 295072895

* Replace base/logging.h with htmlparser/logging.h

PiperOrigin-RevId: 295794452

* Added bazel build files for htmlparser.
Updated README.md with details on building and testing.

PiperOrigin-RevId: 295803731

* Minor bug fixes

PiperOrigin-RevId: 295828454

* Fix error: 'cerr' is not a member of 'std'

PiperOrigin-RevId: 295828491

* Update json testdata.

PiperOrigin-RevId: 295828770

* Update json testfiles.

PiperOrigin-RevId: 295829872

* Update json testdata.

PiperOrigin-RevId: 295831774

* throw runtime error for unknown namespace.

PiperOrigin-RevId: 295835358

* Fix fileutil issue.

PiperOrigin-RevId: 295835589

* Fix std::find errors.

PiperOrigin-RevId: 295851119

* Fixes compiler warnings of wrong types.

PiperOrigin-RevId: 295852676

* Prettify README.md

PiperOrigin-RevId: 295889757

* gulp prettify

PiperOrigin-RevId: 295890877

* prettify 1.json

* prettify 10.json

* prettify 2.json

* prettify 3.json

* prettify 5.json

* prettify 6.json

* prettify 7.json

* prettify 9.json

* replace tabs

* prettify 8.json

* fix json

* json formating

* json formating

* update 7.json

* update 8.json

* Update README.md

Co-authored-by: Amaltas <amaltas@amaltas.org>