test-amp-iframe: Fix consent message races
Tests 'is sent' and 'is sent with empty fields when consent service not
available' used one or two calls of `await macroTask()` before checking
whether the `MessageType.SEND_CONSENT_DATA` listener triggered
`sendConsentDataToIframe_` successfully. These tests were failing due to
a race condition:

      consent-data message
        ✗ is sent
    AssertionError: expected stub to have been called exactly once, but
    it was called 0 times

        ✗ is sent with empty fields when consent service not available
    AssertionError: expected stub to have been called exactly once, but
    it was called 0 times

Wait for sendConsentDataToIframe_ to be called at least once, then allow
another event queue to flush before verifying listener handled message
exactly once.